/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "aix": {
    "base": "aix",
    "width": 1984,
    "height": 1488,
    "fallbackWidth": 1920,
    "fallbackHeight": 1440,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "avignon": {
    "base": "avignon",
    "width": 3840,
    "height": 2880,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "beaches": {
    "base": "beaches",
    "width": 3243,
    "height": 2097,
    "fallbackWidth": 800,
    "fallbackHeight": 517,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "calanques": {
    "base": "calanques",
    "width": 3012,
    "height": 1781,
    "fallbackWidth": 1920,
    "fallbackHeight": 1135,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cassis": {
    "base": "cassis",
    "width": 1024,
    "height": 685,
    "fallbackWidth": 1024,
    "fallbackHeight": 685,
    "widths": [
      320,
      480,
      640,
      800,
      960
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "compare": {
    "base": "compare",
    "width": 1024,
    "height": 685,
    "fallbackWidth": 1024,
    "fallbackHeight": 685,
    "widths": [
      320,
      480,
      640,
      800,
      960
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "corniche": {
    "base": "corniche",
    "width": 1024,
    "height": 579,
    "fallbackWidth": 800,
    "fallbackHeight": 452,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 3648,
    "height": 2432,
    "fallbackWidth": 1920,
    "fallbackHeight": 1280,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "family": {
    "base": "family",
    "width": 3840,
    "height": 2880,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food": {
    "base": "food",
    "width": 3648,
    "height": 2736,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 3840,
    "height": 2880,
    "fallbackWidth": 1920,
    "fallbackHeight": 1440,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "lavender": {
    "base": "lavender",
    "width": 3840,
    "height": 2160,
    "fallbackWidth": 800,
    "fallbackHeight": 450,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "le-panier": {
    "base": "le-panier",
    "width": 1944,
    "height": 2592,
    "fallbackWidth": 800,
    "fallbackHeight": 1067,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "luberon": {
    "base": "luberon",
    "width": 3840,
    "height": 2560,
    "fallbackWidth": 1920,
    "fallbackHeight": 1280,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "markets": {
    "base": "markets",
    "width": 3840,
    "height": 2880,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "mucem": {
    "base": "mucem",
    "width": 3840,
    "height": 2880,
    "fallbackWidth": 1920,
    "fallbackHeight": 1440,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "notre-dame": {
    "base": "notre-dame",
    "width": 3400,
    "height": 4970,
    "fallbackWidth": 1920,
    "fallbackHeight": 2807,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 3400,
    "height": 4970,
    "fallbackWidth": 1920,
    "fallbackHeight": 2807,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "private": {
    "base": "private",
    "width": 3840,
    "height": 2560,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "provence": {
    "base": "provence",
    "width": 3456,
    "height": 2304,
    "fallbackWidth": 1920,
    "fallbackHeight": 1280,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "vieux-port": {
    "base": "vieux-port",
    "width": 720,
    "height": 537,
    "fallbackWidth": 720,
    "fallbackHeight": 537,
    "widths": [
      320,
      480,
      640
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "walking": {
    "base": "walking",
    "width": 3840,
    "height": 5126,
    "fallbackWidth": 800,
    "fallbackHeight": 1068,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "wine": {
    "base": "wine",
    "width": 2560,
    "height": 1920,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
